export default{
    
    ajio:require('./assets/Images/ajio3.png'),
    fb:require('./assets/Images/fb.png'),
    google:require('./assets/Images/google.png'),
    menubar:require('./assets/Images/menubar.png'),
    bell2:require('./assets/Images/bell2.png'),
    search:require('./assets/Images/search.png'),
    treats:require('./assets/Images/treats.jpg'),
    ajio2:require('./assets/Images/ajio2.png'),
   home:require('./assets/Images/home.png'),
   stores:require('./assets/Images/stores.png'),
   account:require('./assets/Images/account.png'),
   wishlist:require('./assets/Images/wishlist.png'),
   logo:require('./assets/Images/logo.png'),
   footer:require('./assets/Images/footer.png'),
   arrow:require('./assets/Images/arrow2.jpg'),
   whatsapp:require('./assets/Images/whatsapp.png'),
   bag:require('./assets/Images/bag.png'),
   invite:require('./assets/Images/invite.png'),
   cross:require('./assets/Images/cross.png'),
   heart1:require('./assets/Images/heart1.png'),
   right:require('./assets/Images/right.png'),
   email:require('./assets/Images/email.png'),
   call:require('./assets/Images/call.png'),
   share:require('./assets/Images/share.png'),
   track:require('./assets/Images/track.png'),
}